name: Build

on:
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }}
    timeout-minutes: 2
    runs-on: ${{ matrix.os }}

    # @see https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.os }}-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        node-version: [22.x]
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/initialize
      - uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
      - name: Test & Build
        run: |
          pnpm build
          pnpm test
        env:
          CI: true
